name: Ourcraft_2
version: ${project.version}
main: com.gabrielmartinmoran.ourcraft.ourcraft_2.Main
api-version: 1.16
authors: [ GabrielMartinMoran ]
description: Ourcraft 2 plugin
depend: [NBTAPI]
commands:
  spellbook:
    description: Otorga al jugador el libro de conjuros especificado
    usage: /<command> <tipo> <nivel>