name: Ourcraft_2
version: ${project.version}
main: com.gabrielmartinmoran.ourcraft.ourcraft_2.Main
api-version: 1.16
authors: [ GabrielMartinMoran ]
description: Ourcraft 2 plugin
depend: [NBTAPI, MythicMobs]
commands:
  spellbook:
    description: Otorga al jugador el libro de conjuros especificado
    usage: /<command> <tipo> <nivel>
  debug:
    description: Opciones de depuracion
    usage: /<command> <metodo>
  stats:
    description: Estadisticas del jugador
    usage: /<command>
  playerdata:
    description: Datos del jugador
    usage: /<command> <metodo>
  memories:
    description: Memorias del jugador
    usage: /<command> <metodo>
  difficultyzone:
    description: Zona de dificultad en la que se encuentra el jugador
    usage: /<command>